### PR TITLE
Add more symbols to symbols.ts and fix the validation for them

### LINKED ISSUE #57: Failed validation: #/definitions/QuoteSummaryResult for symbols AZT.OL, AFRAF, ADH, AMZN, etc.
# Validation for stocks with few pieces of data doesn't work, especially for `quoteSummary`
There are a good few stocks, like `AFRAF`, `AZT.OL`, and `ADH` that don't have enough data for most modules. This needs to be fixed by easing validation and running tests on multiple symbols (#51).

## When this most occurs
When we ask for all modules in `quoteSummary` (via `{ modules: 'all' }`), data is not present for a good few stocks.

## Error occurring
Here is the error for AMZN when asking for all modules:
```js
[
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'regularMarketChangePercent' },
    message: "should have required property 'regularMarketChangePercent'"
  },
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'regularMarketChange' },
    message: "should have required property 'regularMarketChange'"
  },
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'regularMarketPrice' },
    message: "should have required property 'regularMarketPrice'"
  },
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'regularMarketPreviousClose' },
    message: "should have required property 'regularMarketPreviousClose'"
  },
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'currency' },
    message: "should have required property 'currency'"
  },
  {
    keyword: 'required',
    dataPath: '/price',
    schemaPath: '#/definitions/Price/required',
    params: { missingProperty: 'currencySymbol' },
    message: "should have required property 'currencySymbol'"
  }
]
```

## Comments
- This occurs for Amazon, so it seems that it occurs for all sorts of stocks, not just lesser-known ones.

### PR DESCRIPTION
**Pull request by PythonCreator27**
Closes #57
This PR adds more symbols to `symbols.ts` and fixes the validation for the newly added symbols.

## Changes
- Add ~5 symbols to `symbols.ts`
- Fix the validation for the symbols

## Comments
- In the `Grade` enum we already have `Underperform`. This PR adds `Underperformer` to the enum. Was `Underperform` a typo?

## Benefits
- The standard: we catch more validation bugs.

### CODE REVIEW

**Comment by gadicc** [comment]
Thanks, @PythonCreator27, these have been such a great help!  Appreciate all the time you're putting into this!

Re `Grade`, not a typo, this was was auto-detected / auto-generated in the very beginning when I passed a bunch of symbols (though clearly not enough :pensive:) to generate the initial typings.  So glad we have one more in there now :) 

I only have one comment on the PR before we can marge but I'll reply inline for clarity.  Thanks again.

File: src/modules/search.ts [hunk 1]
```diff
@@ -16,32 +16,32 @@ export interface SearchQuoteYahoo {
...
-  quoteType: "CURRENCY";
-  typeDisp: "Currency";
+  quoteType: "CURRENCY" | "FUTURE";
+  typeDisp: "Currency" | "Future";
 }
 export interface SearchQuoteYahooCryptocurrency extends SearchQuoteYahoo {
-  quoteType: "CRYPTOCURRENCY";
-  typeDisp: "Cryptocurrency";
+  quoteType: "CRYPTOCURRENCY" | "FUTURE";
+  typeDisp: "Cryptocurrency" | "Future";
```
Comment (gadicc) [inline src/modules/search.ts:44]: rather than getting all the other types to accept "future" as well, you should rather make a new interface specifically for that type below them, e.g. `SearchQuoteYahooFuture`, and then add that type to the end of the list of quotes types accepted by SearchResult.quotes (should be line 74).

Comment (PythonCreator27) [reply src/modules/search.ts:44]: Sure! Makes sense.

**Comment by gadicc** [comment]
That's great, @PythonCreator27!  Thanks again!
